version: '3'
services:
  db:
    image: 2609666/altair
    environment:
      - POSTGRES_DB=realty
      - POSTGRES_USER=lex
      - POSTGRES_PASSWORD=lex
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db