# Generated by Django 3.0.7 on 2020-06-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('full_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectOfLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Физическое лицо', 'Individual'), ('Юридическое лицо', 'Entity')], default='Юридическое лицо', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WallMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('square', models.FloatField()),
                ('deadline', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='realty.City')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='realty.Developer')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='realty.District')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='realty.Flat')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realty.Image')),
                ('subject_of_law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_of_law', to='realty.SubjectOfLaw')),
                ('wall_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_materials', to='realty.WallMaterial')),
            ],
        ),
    ]
