# Generated by Django 3.0.7 on 2020-06-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flattype',
            name='full_name',
        ),
    ]
